[tool.poetry]
name = "mitzu"
version = "0.6.11"
description = "Product analytics over your data warehouse"
authors = ["Istvan Meszaros <istvan.meszaros.88@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://mitzu.io"
repository = "https://github.com/mitzu-io/mitzu"
documentation = "https://mitzu.io/documentation/"

[tool.poetry.dependencies]
# Core dependencies
python = ">=3.8, <3.11"
pandas = "~1.3.5"
plotly = "~5.5.0"
sqlalchemy = {version="~1.4.31", extras=["asyncio"]}
pyarrow = "~8.0.0"
fastparquet = "~0.8.0"
sqlparse = "^0.4.2"
tqdm = "^4.64.1"
cryptography= "==38.0.4"
requests = "^2.28.2"

# Adapter extras
psycopg2 = {version = "~2.9.3", optional=true}
mysql-connector-python = {version = "~8.0.28", optional=true}
trino = { version = "~0.313.0", optional=true, extras=["sqlalchemy"] }
databricks-sql-connector = { version = "^2.0.2", optional=true}
PyAthena = { version="^2.13.0", optional=true}
snowflake-sqlalchemy = {version = "^1.4.3", optional=true}
snowflake-connector-python = {version = "~=2.8.3", optional=true}
google-cloud-bigquery = {version="^3.10.0", optional=true}
google-cloud-core = {version="^2.3.2", optional=true}
geoalchemy2 = {version= "^0.13.2", optional=true}
shapely =  {version="^2.0.1", optional=true}
google-cloud-bigquery-storage = {version="^2.19.1", optional=true}

# Webapp Extras
dash = {version="~2.8.1", optional=true, extras=["diskcache", "celery", "compress"]}
dash-bootstrap-components = { version="^1.2.0", optional=true}
dash-mantine-components =  { version= "^0.11.1", optional=true}
orjson = {version="^3.7.11", optional=true}
PyJWT = { version="^2.4.0", extras=["crypto"], optional=true}
gunicorn = {version= "^20.1.0", optional=true}
redis =  { version= "^4.4.0", optional=true}
kaleido = {version = "==0.2.1", optional=true}
dash-iconify = {version ="^0.1.2", optional=true}
dash-draggable = {version="^0.1.2", optional=true}
segment-analytics-python = {version="^2.2.2", optional=true}

[tool.poetry.extras]
postgres = ["psycopg2"]
redshift= ["psycopg2"]
mysql = ["mysql-connector-python"]
trinodwh = ["trino"]
databricks = ["databricks-sql-connector"]
athena = ["PyAthena"]
snowflake = ["snowflake-sqlalchemy","snowflake-connector-python"]
bigquery= ["google-cloud-bigquery", "google-cloud-core", "shapely", "geoalchemy2","google-cloud-bigquery-storage"]
webapp = [
    "orjson", 
    "PyJWT", 
    "dash-bootstrap-components",
    "dash-mantine-components", 
    "dash", 
    "dash-iconify", 
    "gunicorn", 
    "redis", 
    "kaleido", 
    "dash-draggable", 
    "segment-analytics-python",
    ]
doc = ["sphinx", "sphinx-autodoc-typehints"]


[tool.poetry.dev-dependencies]
mypy = "^0.982"
pytest = "^6.2.5"
black = "^22.1.0"
pytest-cov = "^3.0.0"
apig-wsgi = "^2.14.0"
types-python-dateutil = "^2.8.18"
flake8 = "^5.0.4"
autoflake = "^1.4"
types-requests = "^2.28.8"
freezegun = "^1.2.2"
pyclean = "^2.2.0"
hypothesis = "^6.71.0"

# Docs
sphinx = "^5.3.0"
sphinx-autodoc-typehints = "^1.19.5"


[tool.poetry.group.dev.dependencies]
types-redis = "^4.3.21.6"
vulture = "^2.6"
black = {extras = ["jupyter"], version = "^22.12.0"}
pylint = "^2.15.9"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
folders = [{ path = "mitzu" }]


[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend =  "poetry_dynamic_versioning.backend"
