[tool.poetry]
name = "emreader"
version = "0.1.9"
description = ""
authors = ["themba <themba@advantch.com>"]
readme = "README.md"
license = "Commercial"
packages = [{include = "src", from = "." }]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
cffi = "^1.15.1"
chardet = "^5.1.0"
charset-normalizer = "^3.1.0"
click = "^8.1.3"
cryptography = "^41.0.1"
distro = "^1.8.0"
et-xmlfile = "^1.1.0"
numpy = "^1.25.0"
opencv-python = "^4.7.0.72"
openpyxl = "^3.1.2"
pandas = "^2.0.2"
pip = "^23.1.2"
pycparser = "^2.21"
PyPDF2 = "2.0"
python-dateutil = "^2.8.2"
pytz = "^2023.3"
setuptools = "^67.7.2"
tabula-py = "2.7.0"
tzdata = "^2023.3"
wheel = "^0.40.0"
rich = "^13.4.2"
streamlit = "^1.23.1"
pymupdf = "^1.22.5"
filestorage = "^0.0.6"
aiofiles = "^23.1.0"

[tool.poetry.scripts]
emreader = "src.runner:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
