[tool.poetry]
name="data_ecosystem_dependencies"
version="202306.0.24"
description="Data Ecosystem  Dependencies - Python (PADE)"
authors=["John Bowyer <zfi4@cdc.gov>"]
readme = "readme.md"
license="Apache"
homepage="https://github.com/cdcent/data_ecosystem_services"
repository="https://github.com/cdcent/data_ecosystem_services"
classifiers=[
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9"
]
include = [ "readme.md",
            "license.md",
            "setup.cfg",
            "setup.py",
            "pyproject.toml"]
packages = [{include = "data_ecosystem_dependencies"}]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.1.2"
python-dotenv = "^1.0.0"
adal = "^1.2.7"
azure-common = "^1.1.28"
azure-keyvault-secrets = "^4.5.0"
azure-identity = "^1.10.0"
azure-storage-file-datalake = "^12.8.0"
openpyxl = "^3.0.4"
numpy = "^1.23.0"
botocore = "1.24.18"
boto3 = "1.21.18"
setuptools = "65.6.3"
requests = "2.31.0"
myst-parser = "^0.18.0"
sphinx-markdown-tables = "^0.0.17"
Sphinx = "^5.2.1"
sphinx-markdown-builder = "^0.5.5"
pathlib = "^1.0.1"
opencensus-ext-azure = "^1.1.7"
opencensus = "^0.11.0"
pyreadstat = "^1.1.9"
sphinx-sitemap = "^2.2.0"
python-dateutil = "^2.8.2"
pygments = "^2.13.0"
markdown = "^3.4.1"
testresources = "^2.0.1"
sphinxcontrib-mermaid = "^0.7.1"
sphinx-autoapi = "^2.0.0"
sphinx-sql = "^1.3.2"
docutils = "0.17.1"
sphinx-autodoc-typehints = "^1.19.5"
pyarrow = "^10.0.1"
rsconnect-jupyter = "^1.6.0"
pytest-cov = "^4.0.0"
sphinx-rtd-theme = "^1.1.1"
chardet = "^5.0.0"
nbconvert = "^6.5.1"
pip-system-certs = "^4.0"
style = "^1.1.6"
azure-keyvault = "^4.2.0"
azure-mgmt-monitor = "^5.0.1"
jinja2 = "^3.1.2"
opentelemetry-sdk = "^1.17.0"
azure-monitor-opentelemetry-exporter = {version = "^1.0.0b14", allow-prereleases = true}
azure-storage-queue = "^12.6.0"

[tool.poetry.dev-dependencies]
pandas = "^1.4.2"
wheel = "^0.38.1"
check-wheel-contents = "^0.3.4"
flake8 = "^4.0.1"
flake8-bugbear = "^22.6.22"
black = "^22.3.0"
commitizen = "^2.28.0"
pathlib = "^1.0.1"
python-decouple = "^3.6"
delta-spark = "2.1.0"
findspark = "^2.0.1"


[tool.pytest.ini_options]
minversion="6.0"
addopts="-ra -q --cov --cov-report html --cov-report term-missing --cov-fail-under 95"
testpaths=[
    "tests"
]

[tool.semantic_release]
version_variable = [ "pyproject.toml:version"]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"

[tool.mypy]
warn_unused_configs=true
namespace_packages=true
explicit_package_bases=true
ignore_missing_imports=true
exclude='tests'



