[tool.poetry]
name = "click-schema-config"
version = "0.1.5"
description = ""
authors = ["Joy Void Joy <joy.void.joy@gmail.com>"]
readme = "README.md"
packages = [{include = "click_schema_config"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"


[tool.poetry.group.dev.dependencies]
black = {version = "^22.8.0", allow-prereleases = true}
mypy = "^1.3.0"
ipython = "^8.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
