[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "apier_bridge"
version = "0.0.2"
authors = [
  { name="camel lu", email="luxuemin2108@gmail.com" },
]
description = "A bridge -- api collection for python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
