[tool.poetry]
name = "prot"
version = "3.10.3"
description = "A Simple Tool That Contains Advance Functions."
authors = ["Aeliux <itsaeliux@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/SAPTeamDEV/prot"
keywords = ["tool", "tools", "protools", "ptools", "colorize"]
classifiers=[
  "Development Status :: 5 - Production/Stable",
  "Topic :: Software Development :: Libraries",
]
packages = [{include = "prot", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8.1"
colorama = "^0.4.6"
docutils = "^0.20.1"

[tool.poetry.scripts]
prot = 'prot:prot'
'prot.pip' = 'prot.pip:pip'

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
commitizen = "^3.3.0"
mypy = "^1.4.0"
types-colorama = "^0.4.15.11"
types-docutils = "^0.20.0.1"
flake8 = "^6.0.0"
pylint = "^2.17.4"
bandit = "^1.7.5"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_type = "semver"
version_provider = "poetry"
version_files = [
    "src/prot/__version__.py"
]
major_version_zero = false
update_changelog_on_bump = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
