[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flowlang"
version = "0.0.3"
authors = [
  { name="Egor Sheremetov", email="egorsheremetov3.0@gmail.com" },
]
description = "An easy way to create and automate natural language processes and tasks."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ESheremetov/Flowlang"
"Bug Tracker" = "https://github.com/ESheremetov/Flowlang/issues"