[tool.poetry]
name = "django-restit"
version = "4.0.1"
description = "A Rest Framework for DJANGO"
authors = ["Ian Starnes <ians@311labs.com>"]
license = "MIT"
readme = "README.md"

packages = [
    {include = "account"},
    {include = "auditlog"},
    {include = "inbox"},
    {include = "incident"},
    {include = "location"},
    {include = "medialib"},
    {include = "metrics"},
    {include = "pushit"},
    {include = "rest"},
    {include = "sessionlog"},
    {include = "taskqueue"},
    {include = "telephony"},
    {include = "ws4redis"}
]

[tool.poetry.dependencies]
python = "^3.8"
pyobjict = "^1.1.6"
django = "*"
uwsgi = "*"
pyjwt = "*"
pycryptodome = "*"
ujson = "*"
twilio = "*"
six = "*"
phonenumbers = "*"
wsaccel = "*"
pycountry = "*"
psutil = "*"
pillow = "*"
pypng = "*"
pygments = "*"
mistune = "*"
inlinestyler = "*"
python-dateutil = "^2.8.2"
hashids = "^1.3.1"
boto3 = "^1.26.160"
pyotp = "^2.8.0"
pyqrcode = "^1.2.1"


[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"
bumpver = "^2023.1124"

[tool.bumpver]
current_version = "4.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = false
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

