[project]
name = "pipebuilder"
version = "0.1.7"
description = "Use LLMs to build pipelines to connect systems."
authors = [
    { name = "Doug Hudgeon", email = "doug.hudgeon@managedfunctions.com" },
]
packages = [
    "pipebuilder",
]
dependencies = [
    "amazon-textract-textractor",
    "arrow",
    "boto3",
    "botocore",
    "click",
    "dateparser",
    "docx2txt",
    "fastparquet",
    "googlemaps",
    "intuit-oauth",
    "langchain",
    "lxml",
    "mail-parser",
    "markdown",
    "numpy",
    "oauthlib",
    "openai",
    "openpyxl",
    "pandas",
    "paramiko",
    "Pillow",
    "PyPDF2",
    "pysftp",
    "python-box",
    "python-dateutil",
    "pytz",
    "PyYAML",
    "rank-bm25",
    "requests",
    "requests-auth-aws-sigv4",
    "requests-oauthlib",
    "sentence-splitter",
    "Unidecode",
    "xlrd",
    "xmltodict",
    "zeep",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.3.2",
]
